#!/usr/bin/env python3
"""Regenerate live/dashboard_html.py from live/dashboard.html.

dashboard.html is the single source of truth for the dashboard; the Python
module embeds it so server.py can serve it without filesystem assumptions.

    python3 -m live.sync_dashboard     (from the repo root)

The volume-profile engine (engineSessionKey / buildProfile) is kept in sync
with live/tvprofile.js, the node-testable extraction:
    node -e "const t=require('./live/tvprofile.js'); ..."   (see README)
"""
import pathlib

root = pathlib.Path(__file__).resolve().parent
html = (root / "dashboard.html").read_text(encoding="utf-8")
assert '"""' not in html, "dashboard.html must not contain triple double-quotes"
out = root / "dashboard_html.py"
out.write_text(
    '"""Self-contained dashboard (inline CSS/JS, no external deps).\n'
    'AUTO-GENERATED from live/dashboard.html — edit that file, then run\n'
    'python3 -m live.sync_dashboard (do not edit this file by hand).\n'
    '"""\n'
    'DASHBOARD_HTML = r"""' + html + '"""\n',
    encoding="utf-8",
)
print(f"wrote {out.name}: {len(html)} bytes embedded")
